### PR TITLE
Integrate new genetic api

### PR DESCRIPTION
**Pull request by Nedelosk**

### CODE REVIEW

**Comment by Nedelosk** [comment]
A new pull request, without any conflicts, this one should be up to date with the 1.14 branch.

**Comment by temp1011** [comment]
Thanks for the amazing work @Nedelosk! Do you want me to open a pull request to the main forestry repo?

**Comment by Nedelosk** [comment]
@temp1011 https://github.com/ForestryMC/ForestryMC/commit/ce96b623e77380a302e6345251c158e93708acf0

**Comment by Nedelosk** [comment]
`3,784 changed files with 106,311 additions and 63,801 deletions.`

**Pull request merged**
